import { type Models } from 'node-appwrite'

// This file is auto-generated by the Appwrite CLI.
// You can regenerate it by running `appwrite types --language ts ./src/types/appwrite.d.ts`.

export type Workspaces = Models.Document & {
  name: string
  userId: string
  imageUrl: string | null
}
