import {
  type Account as AccountType,
  type Databases as DatabasesType,
  type Models,
  type Storage as StorageType
} from 'node-appwrite'

// This file is auto-generated by the Appwrite CLI.
// You can regenerate it by running `appwrite types --language ts ./src/types/appwrite.ts`.

export enum Role {
  ADMIN = 'ADMIN',
  MEMBER = 'MEMBER'
}

export type Workspaces = Models.Document & {
  name: string
  userId: string
  imageUrl: string | null
  inviteCode: string
}

export type Members = Models.Document & {
  userId: string
  workspaceId: string
  role: Role
}

export type MiddleWareContext = {
  Variables: {
    account: AccountType
    databases: DatabasesType
    storage: StorageType
    users: Models.User
    user: Models.User<Models.Preferences>
  }
}
