import { IconName } from 'lucide-react/dynamic'
import { type Models } from 'node-appwrite'

// This file is auto-generated by the Appwrite CLI.
// You can regenerate it by running `appwrite types --language ts ./src/types/appwrite.ts`.

export enum Role {
  ADMIN = 'ADMIN',
  MEMBER = 'MEMBER'
}

export type Workspaces = Models.Row & {
  name: string
  userId: string
  icon: IconName
  slug: string
  theme: 'light' | 'dark' | 'system' | undefined
  description: string
}

export type Members = Models.Row & {
  userId: string
  workspaceId: string
  role: Role
}
