import { QueryProviders } from '@/components/layout/query-provider'
import { ThemeProvider } from '@/components/layout/theme-provider'
import { Toaster } from '@/components/ui/sonner'
import { cn } from '@/lib/utils'
import { Layouts } from '@/types'
import type { Metadata } from 'next'
import { Geist, Geist_Mono, Noto_Sans_Georgian } from 'next/font/google'
import { NuqsAdapter } from 'nuqs/adapters/next/app'
import './globals.css'

const geist = Geist({
  variable: '--font-geist',
  subsets: ['latin']
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
})

const notoSansGeorgian = Noto_Sans_Georgian({
  variable: '--font-noto-sans-georgian',
  subsets: ['georgian']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }: Layouts) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body
        className={cn(
          geist.variable,
          geistMono.variable,
          notoSansGeorgian.variable,
          'antialiased min-h-screen'
        )}
      >
        <NuqsAdapter>
          <QueryProviders>
            <ThemeProvider
              defaultTheme='system'
              themes={['light', 'dark', 'system']}
              attribute='class'
              enableSystem
              disableTransitionOnChange
            >
              {children}
            </ThemeProvider>
          </QueryProviders>
        </NuqsAdapter>
        <Toaster />
      </body>
    </html>
  )
}
