import { QueryProviders } from '@/components/layout/query-provider'
import { ThemeProvider } from '@/components/layout/theme-provider'
import { Toaster } from '@/components/ui/sonner'
import { cn } from '@/lib/utils'
import type { Metadata } from 'next'
import { Oxanium, Source_Code_Pro } from 'next/font/google'
import './globals.css'

const oxanium = Oxanium({
  variable: '--font-oxanium',
  subsets: ['latin']
})

const sourceCodePro = Source_Code_Pro({
  variable: '--font-source-code-pro',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }: Layouts) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body
        className={cn(
          oxanium.variable,
          sourceCodePro.variable,
          'antialiased min-h-screen'
        )}
      >
        <QueryProviders>
          <ThemeProvider
            attribute='class'
            defaultTheme='system'
            enableSystem
            disableTransitionOnChange
          >
            {children}
          </ThemeProvider>
        </QueryProviders>
        <Toaster />
      </body>
    </html>
  )
}
