export const DATABASE_ID = process.env.NEXT_PUBLIC_APPWRITE_DATABASE_ID!
export const APPWRITE_ENDPOINT = process.env.NEXT_PUBLIC_APPWRITE_ENDPOINT!
export const APPWRITE_PROJECT_ID = process.env.NEXT_PUBLIC_APPWRITE_PROJECT_ID!
export const IMAGES_BUCKET_ID =
  process.env.NEXT_PUBLIC_APPWRITE_IMAGES_BUCKET_ID!
export const WORKSPACES_COLLECTION_ID =
  process.env.NEXT_PUBLIC_APPWRITE_WORKSPACES_COLLECTION_ID!
export const MEMBERS_COLLECTION_ID =
  process.env.NEXT_PUBLIC_APPWRITE_MEMBERS_COLLECTION_ID!
export const APPWRITE_API_KEY = process.env.NEXT_APPWRITE_KEY!
export const PROJECTS_COLLECTION_ID =
  process.env.NEXT_PUBLIC_APPWRITE_PROJECTS_COLLECTION_ID!
export const TASKS_COLLECTION_ID =
  process.env.NEXT_PUBLIC_APPWRITE_TASKS_COLLECTION_ID!
export const TASK_COMMENTS_COLLECTION_ID =
  process.env.NEXT_PUBLIC_APPWRITE_TASK_COMMENTS_COLLECTION_ID!
